/*
 * Generated by the Waxeye Parser Generator - version 0.8.1
 * www.waxeye.org
 */

var waxeye = waxeye;
if (typeof module !== 'undefined') {
    // require from module system
    waxeye = require('waxeye');
}

var Parser = (function() {

    var parser = function() { return this; };
    parser.prototype = new waxeye.WaxeyeParser(
        {'Json' : { mode : waxeye.Modes.NORMAL, exp : {type:'SEQ', args:[{type:'NT', args:['Ws']},
            {type:'NT', args:['Value']}]} },
        'Value' : { mode : waxeye.Modes.NORMAL, exp : {type:'SEQ', args:[{type:'ALT', args:[{type:'NT', args:['Object']},
                {type:'NT', args:['Array']},
                {type:'NT', args:['Number']},
                {type:'NT', args:['String']},
                {type:'NT', args:['Literal']}]},
            {type:'NT', args:['Ws']}]} },
        'Object' : { mode : waxeye.Modes.NORMAL, exp : {type:'SEQ', args:[{type:'VOID', args:[{type:'CHAR', args:['{']}]},
            {type:'NT', args:['Ws']},
            {type:'OPT', args:[{type:'SEQ', args:[{type:'NT', args:['Member']},
                    {type:'STAR', args:[{type:'SEQ', args:[{type:'NT', args:['Com']},
                            {type:'NT', args:['Member']}]}]}]}]},
            {type:'VOID', args:[{type:'CHAR', args:['}']}]}]} },
        'Member' : { mode : waxeye.Modes.NORMAL, exp : {type:'SEQ', args:[{type:'NT', args:['String']},
            {type:'NT', args:['Ws']},
            {type:'NT', args:['Col']},
            {type:'NT', args:['Value']}]} },
        'Array' : { mode : waxeye.Modes.NORMAL, exp : {type:'SEQ', args:[{type:'VOID', args:[{type:'CHAR', args:['[']}]},
            {type:'NT', args:['Ws']},
            {type:'OPT', args:[{type:'SEQ', args:[{type:'NT', args:['Value']},
                    {type:'STAR', args:[{type:'SEQ', args:[{type:'NT', args:['Com']},
                            {type:'NT', args:['Value']}]}]}]}]},
            {type:'VOID', args:[{type:'CHAR', args:[']']}]}]} },
        'Number' : { mode : waxeye.Modes.NORMAL, exp : {type:'SEQ', args:[{type:'OPT', args:[{type:'CHAR', args:['-']}]},
            {type:'ALT', args:[{type:'CHAR', args:['0']},
                {type:'SEQ', args:[{type:'CHAR_CLASS', args:[['1', '9']]},
                    {type:'STAR', args:[{type:'CHAR_CLASS', args:[['0', '9']]}]}]}]},
            {type:'OPT', args:[{type:'SEQ', args:[{type:'CHAR', args:['.']},
                    {type:'PLUS', args:[{type:'CHAR_CLASS', args:[['0', '9']]}]}]}]},
            {type:'OPT', args:[{type:'SEQ', args:[{type:'CHAR_CLASS', args:['E',
                        'e']},
                    {type:'OPT', args:[{type:'CHAR_CLASS', args:['+',
                            '-']}]},
                    {type:'PLUS', args:[{type:'CHAR_CLASS', args:[['0', '9']]}]}]}]}]} },
        'String' : { mode : waxeye.Modes.NORMAL, exp : {type:'SEQ', args:[{type:'VOID', args:[{type:'CHAR', args:['\"']}]},
            {type:'STAR', args:[{type:'ALT', args:[{type:'SEQ', args:[{type:'VOID', args:[{type:'CHAR', args:['\\']}]},
                        {type:'NT', args:['Escaped']}]},
                    {type:'SEQ', args:[{type:'NOT', args:[{type:'CHAR', args:['\\']}]},
                        {type:'NOT', args:[{type:'CHAR', args:['\"']}]},
                        {type:'ANY', args:[]}]}]}]},
            {type:'VOID', args:[{type:'CHAR', args:['\"']}]}]} },
        'Escaped' : { mode : waxeye.Modes.NORMAL, exp : {type:'ALT', args:[{type:'SEQ', args:[{type:'CHAR', args:['u']},
                {type:'CHAR_CLASS', args:[['0', '9'],
                    ['A', 'F'],
                    ['a', 'f']]},
                {type:'CHAR_CLASS', args:[['0', '9'],
                    ['A', 'F'],
                    ['a', 'f']]},
                {type:'CHAR_CLASS', args:[['0', '9'],
                    ['A', 'F'],
                    ['a', 'f']]},
                {type:'CHAR_CLASS', args:[['0', '9'],
                    ['A', 'F'],
                    ['a', 'f']]}]},
            {type:'CHAR_CLASS', args:['\"',
                '/',
                '\\',
                'b',
                'f',
                'n',
                'r',
                't']}]} },
        'Literal' : { mode : waxeye.Modes.NORMAL, exp : {type:'ALT', args:[{type:'SEQ', args:[{type:'CHAR', args:['t']},
                {type:'CHAR', args:['r']},
                {type:'CHAR', args:['u']},
                {type:'CHAR', args:['e']}]},
            {type:'SEQ', args:[{type:'CHAR', args:['f']},
                {type:'CHAR', args:['a']},
                {type:'CHAR', args:['l']},
                {type:'CHAR', args:['s']},
                {type:'CHAR', args:['e']}]},
            {type:'SEQ', args:[{type:'CHAR', args:['n']},
                {type:'CHAR', args:['u']},
                {type:'CHAR', args:['l']},
                {type:'CHAR', args:['l']}]}]} },
        'Ws' : { mode : waxeye.Modes.VOIDING, exp : {type:'STAR', args:[{type:'CHAR_CLASS', args:[['\t', '\n'],
                '\r',
                ' ']}]} },
        'Com' : { mode : waxeye.Modes.VOIDING, exp : {type:'SEQ', args:[{type:'CHAR', args:[',']},
            {type:'NT', args:['Ws']}]} },
        'Col' : { mode : waxeye.Modes.VOIDING, exp : {type:'SEQ', args:[{type:'CHAR', args:[':']},
            {type:'NT', args:['Ws']}]} }}
        , 'Json');
    return parser;
 
})();

// Add to module system
if (typeof module !== 'undefined') {
    module.exports.Parser = Parser;
}
