/*
 * Generated by the Waxeye Parser Generator - version 0.7.0
 * www.waxeye.org
 */

var waxeye = waxeye;
if (typeof module !== 'undefined') {
    // require from Node.js module system
    waxeye = require('waxeye');
}

var CalcParser = (function() {

    var parser = function() { return this; };
    parser.prototype = new waxeye.WaxeyeParser(0, true, [new waxeye.FA("calc", [new waxeye.State([new waxeye.Edge(5, 1, false)], false),
            new waxeye.State([new waxeye.Edge(1, 2, false)], false),
            new waxeye.State([], true)], waxeye.FA.LEFT),
        new waxeye.FA("sum", [new waxeye.State([new waxeye.Edge(2, 1, false)], false),
            new waxeye.State([new waxeye.Edge(["+", "-"], 2, false)], true),
            new waxeye.State([new waxeye.Edge(5, 3, false)], false),
            new waxeye.State([new waxeye.Edge(2, 1, false)], false)], waxeye.FA.LEFT),
        new waxeye.FA("prod", [new waxeye.State([new waxeye.Edge(3, 1, false)], false),
            new waxeye.State([new waxeye.Edge(["*", "/"], 2, false)], true),
            new waxeye.State([new waxeye.Edge(5, 3, false)], false),
            new waxeye.State([new waxeye.Edge(3, 1, false)], false)], waxeye.FA.LEFT),
        new waxeye.FA("unary", [new waxeye.State([new waxeye.Edge("-", 1, false),
                new waxeye.Edge("(", 4, true),
                new waxeye.Edge(4, 3, false)], false),
            new waxeye.State([new waxeye.Edge(5, 2, false)], false),
            new waxeye.State([new waxeye.Edge(3, 3, false)], false),
            new waxeye.State([], true),
            new waxeye.State([new waxeye.Edge(5, 5, false)], false),
            new waxeye.State([new waxeye.Edge(1, 6, false)], false),
            new waxeye.State([new waxeye.Edge(")", 7, true)], false),
            new waxeye.State([new waxeye.Edge(5, 3, false)], false)], waxeye.FA.PRUNE),
        new waxeye.FA("num", [new waxeye.State([new waxeye.Edge([[48, 57]], 1, false)], false),
            new waxeye.State([new waxeye.Edge([[48, 57]], 1, false),
                new waxeye.Edge(".", 2, false),
                new waxeye.Edge(5, 4, false)], false),
            new waxeye.State([new waxeye.Edge([[48, 57]], 3, false)], false),
            new waxeye.State([new waxeye.Edge([[48, 57]], 3, false),
                new waxeye.Edge(5, 4, false)], false),
            new waxeye.State([], true)], waxeye.FA.LEFT),
        new waxeye.FA("ws", [new waxeye.State([new waxeye.Edge([[9, 10], "\r", " "], 0, false)], true)], waxeye.FA.VOID)]);
    return parser;
 
})();

// Add to Node.js module system
if (typeof module !== 'undefined') {
    module.exports.CalcParser = CalcParser;
}
