<?php

use parser\config\Automata;
use parser\config\Automaton;
use parser\config\ParserConfig;
use parser\expression\Expression;
use parser\NonTerminalMode;
use parser\Parser;

class WaxeyeGrammarParser extends Parser
{
    public function __construct()
    {
        $automata = new Automata();

        $automata["Grammar"] = new Automaton("Grammar", NonTerminalMode::NORMAL, Expression::SeqExpression(Expression::NonTerminalExpression("Ws"), Expression::StarExpression(Expression::NonTerminalExpression("Definition"))));
        $automata["Definition"] = new Automaton("Definition", NonTerminalMode::NORMAL, Expression::SeqExpression(Expression::NonTerminalExpression("Identifier"), Expression::AltExpression(Expression::NonTerminalExpression("LeftArrow"), Expression::NonTerminalExpression("PruneArrow"), Expression::NonTerminalExpression("VoidArrow")), Expression::NonTerminalExpression("Alternation"), Expression::NonTerminalExpression("Ws")));
        $automata["Alternation"] = new Automaton("Alternation", NonTerminalMode::NORMAL, Expression::SeqExpression(Expression::NonTerminalExpression("Sequence"), Expression::StarExpression(Expression::SeqExpression(Expression::NonTerminalExpression("Alt"), Expression::NonTerminalExpression("Sequence")))));
        $automata["Sequence"] = new Automaton("Sequence", NonTerminalMode::NORMAL, Expression::PlusExpression(Expression::NonTerminalExpression("Unit")));
        $automata["Unit"] = new Automaton("Unit", NonTerminalMode::NORMAL, Expression::SeqExpression(Expression::StarExpression(Expression::AltExpression(Expression::NonTerminalExpression("Prefix"), Expression::NonTerminalExpression("Label"))), Expression::AltExpression(Expression::SeqExpression(Expression::NonTerminalExpression("Identifier"), Expression::NotExpression(Expression::AltExpression(Expression::NonTerminalExpression("LeftArrow"), Expression::NonTerminalExpression("PruneArrow"), Expression::NonTerminalExpression("VoidArrow")))), Expression::SeqExpression(Expression::NonTerminalExpression("Open"), Expression::NonTerminalExpression("Alternation"), Expression::NonTerminalExpression("Close")), Expression::NonTerminalExpression("Action"), Expression::NonTerminalExpression("Literal"), Expression::NonTerminalExpression("CaseLiteral"), Expression::NonTerminalExpression("CharClass"), Expression::NonTerminalExpression("WildCard"))));
        $automata["Prefix"] = new Automaton("Prefix", NonTerminalMode::NORMAL, Expression::SeqExpression(Expression::CharClassExpression(array(33, 38, 58, 63), array(42), array(43)), Expression::NonTerminalExpression("Ws")));
        $automata["Label"] = new Automaton("Label", NonTerminalMode::NORMAL, Expression::SeqExpression(Expression::NonTerminalExpression("Identifier"), Expression::NonTerminalExpression("Ws"), Expression::VoidExpression(Expression::CharExpression(61)), Expression::NonTerminalExpression("Ws")));
        $automata["Action"] = new Automaton("Action", NonTerminalMode::NORMAL, Expression::SeqExpression(Expression::VoidExpression(Expression::CharExpression(64)), Expression::NonTerminalExpression("Identifier"), Expression::OptExpression(Expression::SeqExpression(Expression::VoidExpression(Expression::CharExpression(60)), Expression::NonTerminalExpression("Ws"), Expression::NonTerminalExpression("Identifier"), Expression::StarExpression(Expression::SeqExpression(Expression::NonTerminalExpression("Comma"), Expression::NonTerminalExpression("Identifier"))), Expression::VoidExpression(Expression::CharExpression(62)))), Expression::NonTerminalExpression("Ws")));
        $automata["Identifier"] = new Automaton("Identifier", NonTerminalMode::NORMAL, Expression::SeqExpression(Expression::CharClassExpression(array(95), array(65, 97), array(90, 122)), Expression::StarExpression(Expression::CharClassExpression(array(45, 95), array(48, 65, 97), array(57, 90, 122))), Expression::NonTerminalExpression("Ws")));
        $automata["Literal"] = new Automaton("Literal", NonTerminalMode::NORMAL, Expression::SeqExpression(Expression::VoidExpression(Expression::CharClassExpression(array(39), array(), array())), Expression::PlusExpression(Expression::SeqExpression(Expression::NotExpression(Expression::CharClassExpression(array(39), array(), array())), Expression::AltExpression(Expression::NonTerminalExpression("LChar"), Expression::NonTerminalExpression("Hex")))), Expression::VoidExpression(Expression::CharClassExpression(array(39), array(), array())), Expression::NonTerminalExpression("Ws")));
        $automata["CaseLiteral"] = new Automaton("CaseLiteral", NonTerminalMode::NORMAL, Expression::SeqExpression(Expression::VoidExpression(Expression::CharClassExpression(array(34), array(), array())), Expression::PlusExpression(Expression::SeqExpression(Expression::NotExpression(Expression::CharClassExpression(array(34), array(), array())), Expression::AltExpression(Expression::NonTerminalExpression("LChar"), Expression::NonTerminalExpression("Hex")))), Expression::VoidExpression(Expression::CharClassExpression(array(34), array(), array())), Expression::NonTerminalExpression("Ws")));
        $automata["LChar"] = new Automaton("LChar", NonTerminalMode::NORMAL, Expression::AltExpression(Expression::SeqExpression(Expression::CharExpression(92), Expression::CharClassExpression(array(34, 39, 92, 110, 114, 116), array(), array())), Expression::SeqExpression(Expression::NotExpression(Expression::CharExpression(92)), Expression::NotExpression(Expression::NonTerminalExpression("EndOfLine")), Expression::AnyCharExpression())));
        $automata["CharClass"] = new Automaton("CharClass", NonTerminalMode::NORMAL, Expression::SeqExpression(Expression::VoidExpression(Expression::CharExpression(91)), Expression::StarExpression(Expression::SeqExpression(Expression::NotExpression(Expression::CharExpression(93)), Expression::NonTerminalExpression("Range"))), Expression::VoidExpression(Expression::CharExpression(93)), Expression::NonTerminalExpression("Ws")));
        $automata["Range"] = new Automaton("Range", NonTerminalMode::NORMAL, Expression::SeqExpression(Expression::AltExpression(Expression::NonTerminalExpression("Char"), Expression::NonTerminalExpression("Hex")), Expression::OptExpression(Expression::SeqExpression(Expression::VoidExpression(Expression::CharExpression(45)), Expression::AltExpression(Expression::NonTerminalExpression("Char"), Expression::NonTerminalExpression("Hex"))))));
        $automata["Char"] = new Automaton("Char", NonTerminalMode::NORMAL, Expression::AltExpression(Expression::SeqExpression(Expression::CharExpression(92), Expression::CharClassExpression(array(45, 110, 114, 116), array(92), array(93))), Expression::SeqExpression(Expression::NotExpression(Expression::CharExpression(92)), Expression::NotExpression(Expression::CharExpression(93)), Expression::NotExpression(Expression::NonTerminalExpression("EndOfLine")), Expression::AnyCharExpression())));
        $automata["Hex"] = new Automaton("Hex", NonTerminalMode::NORMAL, Expression::SeqExpression(Expression::VoidExpression(Expression::SeqExpression(Expression::CharExpression(92), Expression::CharExpression(117), Expression::CharExpression(123))), Expression::CharClassExpression(array(), array(48, 65, 97), array(57, 70, 102)), Expression::OptExpression(Expression::CharClassExpression(array(), array(48, 65, 97), array(57, 70, 102))), Expression::OptExpression(Expression::CharClassExpression(array(), array(48, 65, 97), array(57, 70, 102))), Expression::OptExpression(Expression::CharClassExpression(array(), array(48, 65, 97), array(57, 70, 102))), Expression::OptExpression(Expression::CharClassExpression(array(), array(48, 65, 97), array(57, 70, 102))), Expression::OptExpression(Expression::CharClassExpression(array(), array(48, 65, 97), array(57, 70, 102))), Expression::VoidExpression(Expression::CharExpression(125))));
        $automata["WildCard"] = new Automaton("WildCard", NonTerminalMode::NORMAL, Expression::SeqExpression(Expression::VoidExpression(Expression::CharExpression(46)), Expression::NonTerminalExpression("Ws")));
        $automata["LeftArrow"] = new Automaton("LeftArrow", NonTerminalMode::NORMAL, Expression::SeqExpression(Expression::VoidExpression(Expression::SeqExpression(Expression::CharExpression(60), Expression::CharExpression(45))), Expression::NonTerminalExpression("Ws")));
        $automata["PruneArrow"] = new Automaton("PruneArrow", NonTerminalMode::NORMAL, Expression::SeqExpression(Expression::VoidExpression(Expression::SeqExpression(Expression::CharExpression(60), Expression::CharExpression(61))), Expression::NonTerminalExpression("Ws")));
        $automata["VoidArrow"] = new Automaton("VoidArrow", NonTerminalMode::NORMAL, Expression::SeqExpression(Expression::VoidExpression(Expression::SeqExpression(Expression::CharExpression(60), Expression::CharExpression(58))), Expression::NonTerminalExpression("Ws")));
        $automata["Alt"] = new Automaton("Alt", NonTerminalMode::VOIDING, Expression::SeqExpression(Expression::CharExpression(124), Expression::NonTerminalExpression("Ws")));
        $automata["Open"] = new Automaton("Open", NonTerminalMode::VOIDING, Expression::SeqExpression(Expression::CharExpression(40), Expression::NonTerminalExpression("Ws")));
        $automata["Close"] = new Automaton("Close", NonTerminalMode::VOIDING, Expression::SeqExpression(Expression::CharExpression(41), Expression::NonTerminalExpression("Ws")));
        $automata["Comma"] = new Automaton("Comma", NonTerminalMode::VOIDING, Expression::SeqExpression(Expression::CharExpression(44), Expression::NonTerminalExpression("Ws")));
        $automata["SComment"] = new Automaton("SComment", NonTerminalMode::VOIDING, Expression::SeqExpression(Expression::CharExpression(35), Expression::StarExpression(Expression::SeqExpression(Expression::NotExpression(Expression::NonTerminalExpression("EndOfLine")), Expression::AnyCharExpression())), Expression::AltExpression(Expression::NonTerminalExpression("EndOfLine"), Expression::NotExpression(Expression::AnyCharExpression()))));
        $automata["MComment"] = new Automaton("MComment", NonTerminalMode::VOIDING, Expression::SeqExpression(Expression::SeqExpression(Expression::CharExpression(47), Expression::CharExpression(42)), Expression::StarExpression(Expression::AltExpression(Expression::NonTerminalExpression("MComment"), Expression::SeqExpression(Expression::NotExpression(Expression::SeqExpression(Expression::CharExpression(42), Expression::CharExpression(47))), Expression::AnyCharExpression()))), Expression::SeqExpression(Expression::CharExpression(42), Expression::CharExpression(47))));
        $automata["EndOfLine"] = new Automaton("EndOfLine", NonTerminalMode::VOIDING, Expression::AltExpression(Expression::SeqExpression(Expression::CharExpression(13), Expression::CharExpression(10)), Expression::CharExpression(10), Expression::CharExpression(13)));
        $automata["Ws"] = new Automaton("Ws", NonTerminalMode::VOIDING, Expression::StarExpression(Expression::AltExpression(Expression::CharClassExpression(array(9, 32), array(), array()), Expression::NonTerminalExpression("EndOfLine"), Expression::NonTerminalExpression("SComment"), Expression::NonTerminalExpression("MComment"))));
        $config = new ParserConfig($automata, "Grammar");
        parent::__construct($config);
    }
}
